// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RimDialogue
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using RimDialogue.Core;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class PromptTemplate : PromptTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nYou are a dialogue writer for the game RimWorld. Your job is to create a dialog" +
                    "ue exchange of ");
            
            #line 8 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.maxWords));
            
            #line default
            #line hidden
            this.Write(" words or less total between ");
            
            #line 8 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 8 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" based primarily on the following interaction: ");
            
            #line 8 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.interaction));
            
            #line default
            #line hidden
            this.Write("\r\nStart the dialogue with ");
            
            #line 9 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s part in the interaction.\r\nAlways put ");
            
            #line 10 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s and ");
            
            #line 10 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s name in the dialogue.\r\nIt is important that you respond with only the dialogue" +
                    " exchange. Do not include any additional information or context.\r\n");
            
            #line 12 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.specialInstructions));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nUse the following information to help shape ");
            
            #line 14 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s and ");
            
            #line 14 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s tone, word choice, and attitude.\r\n");
            
            #line 15 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 15 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" are pawns in the game RimWorld.\r\n");
            
            #line 16 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s full name is ");
            
            #line 16 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorFullName));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 17 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s full name is ");
            
            #line 17 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientFullName));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 18 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s gender is ");
            
            #line 18 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorGender));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 19 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s gender is ");
            
            #line 19 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientGender));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 20 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s race is ");
            
            #line 20 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorRace));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 21 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s race is ");
            
            #line 21 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientRace));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 22 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s subrace is ");
            
            #line 22 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 23 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s subrace is ");
            
            #line 23 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 24 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorIsAnimal) { 
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" is an animal. ");
            
            #line 25 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" can\'t speak, but they can communicate through actions, sounds, and body language" +
                    ". C\r\n");
            
            #line 26 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientIsAnimal) { 
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" is an animal. ");
            
            #line 28 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" can\'t speak, but they can communicate through actions, sounds, and body language" +
                    ".\r\n");
            
            #line 29 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s age is ");
            
            #line 30 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorAge));
            
            #line default
            #line hidden
            this.Write(" years old.\r\n");
            
            #line 31 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s age is ");
            
            #line 31 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientAge));
            
            #line default
            #line hidden
            this.Write(" years old.\r\n");
            
            #line 32 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" is");
            
            #line 32 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorIsColonist ? " " : " not "));
            
            #line default
            #line hidden
            this.Write("a colonist.\r\n");
            
            #line 33 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" is");
            
            #line 33 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientIsColonist ? " " : " not "));
            
            #line default
            #line hidden
            this.Write("a colonist.\r\n");
            
            #line 34 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.initiatorIsColonist || !this.DialogueData.recipientIsColonist) { 
            
            #line default
            #line hidden
            this.Write("Pawns who are not colonists or animals are just temporary visitors to the colony." +
                    "  They might be traders, raiders, or just visitors. \r\n");
            
            #line 36 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" is");
            
            #line 37 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorIsPrisoner ? " " : " not "));
            
            #line default
            #line hidden
            this.Write("a prisoner. \r\n");
            
            #line 38 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" is");
            
            #line 38 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientIsPrisoner ? " " : " not "));
            
            #line default
            #line hidden
            this.Write("a prisoner. \r\n");
            
            #line 39 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorRoyaltyTitle)) { 
            
            #line default
            #line hidden
            
            #line 40 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" is royalty. Pawns speak differently to royalty, often with more respect and form" +
                    "ality.\r\n");
            
            #line 41 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s royal title is ");
            
            #line 41 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorRoyaltyTitle));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 42 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 43 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientRoyaltyTitle)) { 
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientRoyaltyTitle));
            
            #line default
            #line hidden
            this.Write(" is royalty. Pawns speak differently to royalty, often with more respect and form" +
                    "ality.\r\n");
            
            #line 45 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s royal title is ");
            
            #line 45 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientRoyaltyTitle));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 46 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorHair)) { 
            
            #line default
            #line hidden
            
            #line 48 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s hair style is ");
            
            #line 48 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorHair));
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 49 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 50 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientHair)) { 
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s hair style is ");
            
            #line 51 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientHair));
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 52 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorBeard) || this.DialogueData.initiatorBeard == "no beard") { 
            
            #line default
            #line hidden
            
            #line 54 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorGender != "female") { 
            
            #line default
            #line hidden
            
            #line 55 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" does not have a beard.\r\n");
            
            #line 56 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 57 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 58 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s beard style is ");
            
            #line 58 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorBeard));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 59 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 60 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientBeard) || this.DialogueData.recipientBeard == "no beard") { 
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientGender != "female") { 
            
            #line default
            #line hidden
            
            #line 62 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" does not have a beard.\r\n");
            
            #line 63 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 64 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 65 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s beard style is ");
            
            #line 65 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientBeard));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 66 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 67 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorFaceTattoo) && this.DialogueData.initiatorFaceTattoo != "none") { 
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" has a face tattoo of a ");
            
            #line 68 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorFaceTattoo));
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 69 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientFaceTattoo) && this.DialogueData.recipientFaceTattoo != "none") { 
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" has a face tattoo of a ");
            
            #line 71 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientFaceTattoo));
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 72 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorBodyTattoo) && this.DialogueData.initiatorBodyTattoo != "none") { 
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" has body tattoo of a ");
            
            #line 74 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorBodyTattoo));
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 75 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientBodyTattoo) && this.DialogueData.recipientBodyTattoo != "none") { 
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" has body tattoo of a ");
            
            #line 77 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientBodyTattoo));
            
            #line default
            #line hidden
            this.Write(" \r\n");
            
            #line 78 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 79 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorIsPrisoner || this.DialogueData.recipientIsPrisoner) { 
            
            #line default
            #line hidden
            this.Write(@"In RimWorld, prisoners play a complex role, as they can be both valuable resources and potential threats. Captured characters are held in designated prison cells, where colonists provide for their basic needs, like food, medical care, and sometimes recreational activities, to keep them content and prevent escape attempts. Prisoners can serve various purposes: they can be recruited to join the colony, traded with visiting factions, or even used for labor or medical resources like organ harvesting (though these actions can negatively impact colony morale). Recruitable prisoners require attention to their mood, health, and resistance level, as colonists must reduce their resistance through repeated ""recruit"" interactions to eventually persuade them to join. ");
            
            #line 79 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("The faction ");
            
            #line 80 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" belongs to is called \"");
            
            #line 80 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorFactionName));
            
            #line default
            #line hidden
            this.Write("\".\r\nThe faction ");
            
            #line 81 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" belongs to is called \"");
            
            #line 81 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientFactionName));
            
            #line default
            #line hidden
            this.Write("\".\r\n");
            
            #line 82 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorIdeology)) { 
            
            #line default
            #line hidden
            
            #line 83 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology is ");
            
            #line 83 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorIdeology));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 84 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorIdeologyPrecepts.Any()) {
            
            #line default
            #line hidden
            this.Write("The precepts of ");
            
            #line 85 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology are: ");
            
            #line 85 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.initiatorIdeologyPrecepts)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 86 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 }} 
            
            #line default
            #line hidden
            
            #line 87 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientIdeology)) { 
            
            #line default
            #line hidden
            
            #line 88 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology is ");
            
            #line 88 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientIdeology));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 89 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientIdeologyPrecepts.Any()) {
            
            #line default
            #line hidden
            this.Write("The precepts of ");
            
            #line 90 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology are: ");
            
            #line 90 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.recipientIdeologyPrecepts)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 91 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 }} 
            
            #line default
            #line hidden
            
            #line 92 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorAdulthood)) { 
            
            #line default
            #line hidden
            
            #line 93 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s profession is: ");
            
            #line 93 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorAdulthood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 94 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 95 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientAdulthood)) { 
            
            #line default
            #line hidden
            
            #line 96 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s profession is: ");
            
            #line 96 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientAdulthood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 97 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 98 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorChildhood)) { 
            
            #line default
            #line hidden
            
            #line 99 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s childhood was spent as: ");
            
            #line 99 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorChildhood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 100 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 101 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientChildhood)) { 
            
            #line default
            #line hidden
            
            #line 102 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s childhood was spent as: ");
            
            #line 102 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientChildhood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 103 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 104 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.initiatorRelations.Any()) { 
            
            #line default
            #line hidden
            
            #line 105 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s family relations are: ");
            
            #line 105 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.initiatorRelations)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 106 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 107 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.recipientRelations.Any()) { 
            
            #line default
            #line hidden
            
            #line 108 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s family relations are: ");
            
            #line 108 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.recipientRelations)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 109 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 110 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.initiatorTraits.Any()) { 
            
            #line default
            #line hidden
            
            #line 111 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s traits are: ");
            
            #line 111 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.initiatorTraits)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 112 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 113 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.recipientTraits.Any()) { 
            
            #line default
            #line hidden
            
            #line 114 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s traits are: ");
            
            #line 114 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.recipientTraits)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 115 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 116 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.initiatorSkills.Any()) { 
            
            #line default
            #line hidden
            
            #line 117 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s skills are: ");
            
            #line 117 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.initiatorSkills)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 118 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 119 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.recipientSkills.Any()) { 
            
            #line default
            #line hidden
            
            #line 120 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s skills are: ");
            
            #line 120 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.recipientSkills)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 121 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 122 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.initiatorMoodThoughts.Any()) { 
            
            #line default
            #line hidden
            
            #line 123 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s recent thoughts are: ");
            
            #line 123 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetThoughts(this.DialogueData.initiatorNickName, this.DialogueData.initiatorMoodThoughts)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 124 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 125 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!this.DialogueData.recipientMoodThoughts.Any()) { 
            
            #line default
            #line hidden
            
            #line 126 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s recent thoughts are: ");
            
            #line 126 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetThoughts(this.DialogueData.recipientNickName, this.DialogueData.recipientMoodThoughts)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 127 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 128 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorHediffs.Any()) { 
            
            #line default
            #line hidden
            
            #line 129 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s health conditions are: ");
            
            #line 129 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.initiatorHediffs)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 130 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 131 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientHediffs.Any()) { 
            
            #line default
            #line hidden
            
            #line 132 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s health conditions are: ");
            
            #line 132 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.recipientHediffs)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 133 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 134 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorApparel.Any()) { 
            
            #line default
            #line hidden
            
            #line 135 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s apparel is: ");
            
            #line 135 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.initiatorApparel)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 136 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 137 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientApparel.Any()) { 
            
            #line default
            #line hidden
            
            #line 138 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s apparel is: ");
            
            #line 138 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.recipientApparel)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 139 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 140 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorWeapons.Any()) { 
            
            #line default
            #line hidden
            
            #line 141 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s weapons and equipment are: ");
            
            #line 141 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.initiatorWeapons)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 142 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 143 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientWeapons.Any()) { 
            
            #line default
            #line hidden
            
            #line 144 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s weapons and equipment are: ");
            
            #line 144 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", this.DialogueData.recipientWeapons)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 145 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 146 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.initiatorMoodString)) { 
            
            #line default
            #line hidden
            
            #line 147 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s overall mood is ");
            
            #line 147 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorMoodString));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 148 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 149 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.DialogueData.recipientMoodString)) { 
            
            #line default
            #line hidden
            
            #line 150 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s overall mood is ");
            
            #line 150 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientMoodString));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 151 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("Comfort satisfaction reflects how physically comfortable a colonist feels.\r\n");
            
            #line 153 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorComfortPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 154 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s comfort satisfaction is ");
            
            #line 154 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.initiatorComfortPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 155 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 156 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientComfortPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 157 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s comfort satisfaction is ");
            
            #line 157 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.recipientComfortPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 158 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("Food satisfaction represents hunger and the quality of meals. \r\n");
            
            #line 160 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorFoodPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 161 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s food satisfaction is ");
            
            #line 161 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.initiatorFoodPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 162 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 163 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientFoodPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 164 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s food satisfaction is ");
            
            #line 164 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.recipientFoodPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 165 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("Rest satisfaction tracks each colonist\'s need for sleep.\r\n");
            
            #line 167 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorRestPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 168 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s rest satisfaction is ");
            
            #line 168 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.initiatorRestPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 169 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 170 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientRestPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 171 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s rest satisfaction is ");
            
            #line 171 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.recipientRestPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 172 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("Joy satisfaction (or recreation) measures the fulfillment of a colonist\'s need fo" +
                    "r leisure activities, like playing horseshoes or watching television.\r\n");
            
            #line 174 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorJoyPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 175 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s joy satisfaction is ");
            
            #line 175 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.initiatorJoyPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 176 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 177 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientJoyPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 178 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s joy satisfaction is ");
            
            #line 178 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.recipientJoyPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 179 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("Beauty satisfaction is a pawn’s satisfaction with their environment\'s visual appe" +
                    "al.\r\n");
            
            #line 181 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorBeautyPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 182 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s beauty satisfaction is ");
            
            #line 182 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.initiatorBeautyPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 183 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 184 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientBeautyPercentage >= 0) { 
            
            #line default
            #line hidden
            
            #line 185 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s beauty satisfaction is ");
            
            #line 185 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PercentToLabel(this.DialogueData.recipientBeautyPercentage)));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 186 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 187 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorOpinionOfRecipient.Any() || this.DialogueData.recipientOpinionOfInitiator.Any()) { 
            
            #line default
            #line hidden
            this.Write("Use recent interactions provided to affect how positive or negative ");
            
            #line 188 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 188 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" feel about each other.\r\n");
            
            #line 189 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 190 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.initiatorOpinionOfRecipient.Any()) { 
            
            #line default
            #line hidden
            
            #line 191 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s recent interactions with ");
            
            #line 191 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" are: ");
            
            #line 191 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetThoughts(this.DialogueData.initiatorNickName, this.DialogueData.initiatorOpinionOfRecipient)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 192 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 193 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.recipientOpinionOfInitiator.Any()) { 
            
            #line default
            #line hidden
            
            #line 194 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s recent interactions with ");
            
            #line 194 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" are: ");
            
            #line 194 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetThoughts(this.DialogueData.recipientNickName, this.DialogueData.recipientOpinionOfInitiator)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 195 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 196 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.InitiatorConversations != null && this.InitiatorConversations.Any()) { 
            
            #line default
            #line hidden
            this.Write("Use these past conversations provided to create consistent themes, word choice, a" +
                    "nd attitude for ");
            
            #line 197 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(":\r\n");
            
            #line 198 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 foreach (var conversation in this.InitiatorConversations) { 
            
            #line default
            #line hidden
            this.Write("The interaction \"");
            
            #line 199 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(conversation.Interaction));
            
            #line default
            #line hidden
            this.Write("\" resulted in this conversation: \r\n");
            
            #line 200 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(conversation.Dialogue));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 202 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 }} 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 204 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.RecipientConversations != null && this.RecipientConversations.Any()) { 
            
            #line default
            #line hidden
            this.Write("Use these past conversations provided to create consistent themes, word choice, a" +
                    "nd attitude for ");
            
            #line 205 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(":\r\n");
            
            #line 206 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 foreach (var conversation in this.RecipientConversations) { 
            
            #line default
            #line hidden
            this.Write("The interaction was: ");
            
            #line 207 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(conversation.Interaction));
            
            #line default
            #line hidden
            this.Write("\r\nThe dialogue of the conversation was: ");
            
            #line 208 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(conversation.Dialogue));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 210 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 }} 
            
            #line default
            #line hidden
            this.Write(@"
RimWorld is a sci-fi colony simulation game where players manage a group of characters stranded on a distant, lawless planet. Combining elements of survival, resource management, and storytelling, the game challenges players to build and protect a thriving colony amid constant threats, including brutal weather, raids from hostile factions, and mysterious alien wildlife. Each colonist has unique skills, backstories, and personalities, which shape their behavior and interactions, often leading to complex social dynamics, rivalries, and bonds. The game uses an AI storyteller to randomly generate events that range from disease outbreaks to alien attacks, tailoring the gameplay experience to be intense, unpredictable, and highly replayable. Players can customize and expand their colony, conduct research, defend against raids, and ultimately aim to escape the planet—or embrace its challenges indefinitely.
When pawns have an interaction and speak to each other about a subject, they are speaking about the subject in the abstract and the subject is not something that is present with them.  Pawns often speaks wistfully about subjects they desire.     
Lovin' is a euphemism for sex.

The colony started with this scenario: """);
            
            #line 216 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.scenario));
            
            #line default
            #line hidden
            this.Write("\"\r\nThe colony started ");
            
            #line 217 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DaysAgoLabel));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 218 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.WealthDescription(this.DialogueData.wealthTotal)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nThe biome of the colony is ");
            
            #line 220 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.biome));
            
            #line default
            #line hidden
            this.Write("\r\nThe current weather in the colony is ");
            
            #line 221 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.currentWeather));
            
            #line default
            #line hidden
            this.Write("\r\nThe temperature outdoors in the colony is ");
            
            #line 222 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemperatureFeel(this.DialogueData.outdoorTemp)));
            
            #line default
            #line hidden
            this.Write(".\r\nRecent incidents to occur in the colony are: ");
            
            #line 223 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ",this.DialogueData.recentIncidents)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 224 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 if (this.DialogueData.isOutside) { 
            
            #line default
            #line hidden
            
            #line 225 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 225 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" are currently outside.\r\n");
            
            #line 226 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 227 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 227 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" are currently indoors.\r\nThe room where ");
            
            #line 228 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 228 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" are currently located is: ");
            
            #line 228 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.room));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 229 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nYou are a dialogue writer for the game RimWorld. Your job is to create a dialog" +
                    "ue exchange of ");
            
            #line 231 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.maxWords));
            
            #line default
            #line hidden
            this.Write(" words or less total between ");
            
            #line 231 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 231 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write(" based primarily on the following interaction: ");
            
            #line 231 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.interaction));
            
            #line default
            #line hidden
            this.Write("\r\nStart the dialogue with ");
            
            #line 232 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s part in the interaction.\r\nAlways put ");
            
            #line 233 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.initiatorNickName));
            
            #line default
            #line hidden
            this.Write("\'s and ");
            
            #line 233 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.recipientNickName));
            
            #line default
            #line hidden
            this.Write("\'s name in the dialogue.\r\nIt is important that you respond with only the dialogue" +
                    " exchange. Do not include any additional information or context.\r\n");
            
            #line 235 "C:\Users\madja\source\repos\RimDialogue\RimDialogue\PromptTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.DialogueData.specialInstructions));
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class PromptTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
