// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RimDialogueObjects.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using RimDialogue.Core;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class InitiatorRecipientTemplate : InitiatorRecipientTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nHere is background information about ");
            
            #line 8 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 8 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(". Use this information to help you write the conversation from their perspectives" +
                    ".\r\nAlways put ");
            
            #line 9 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s and ");
            
            #line 9 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s name in the dialogue.\r\n");
            
            #line 10 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowSpecialInstructions) { 
            
            #line default
            #line hidden
            
            #line 11 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
  if (!string.IsNullOrWhiteSpace(this.Initiator.Instructions)) { 
            
            #line default
            #line hidden
            this.Write("Instructions for ");
            
            #line 12 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 12 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Instructions));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 13 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
  if (!string.IsNullOrWhiteSpace(this.Recipient.Instructions)) { 
            
            #line default
            #line hidden
            this.Write("Instructions for ");
            
            #line 15 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 15 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.Instructions));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 16 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowOpinions) { 
            
            #line default
            #line hidden
            this.Write("Opinion affects how ");
            
            #line 19 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 19 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" feel about each other and how they will respond to each other.\r\n");
            
            #line 20 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelper.DescribeOpinion(this.InitiatorOpinionOfRecipient)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 21 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplateHelper.DescribeOpinion(this.RecipientOpinionOfInitiator)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 22 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowAnimal && this.Initiator.IsAnimal) { 
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" can\'t speak, but they can communicate through actions, sounds, and body language" +
                    ".\r\n");
            
            #line 25 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowAnimal && this.Recipient.IsAnimal) { 
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" can\'t speak, but they can communicate through actions, sounds, and body language" +
                    ".\r\n");
            
            #line 28 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowPersonality) { 
            
            #line default
            #line hidden
            this.Write("Personality affects how ");
            
            #line 30 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 30 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" behave and interact with each other.\r\n");
            
            #line 31 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Initiator.Personality)) { 
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s personality is ");
            
            #line 32 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Personality));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 33 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.PersonalityDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 34 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Recipient.Personality)) { 
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s personality is ");
            
            #line 37 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.Personality));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 38 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.PersonalityDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 39 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("Mood is how ");
            
            #line 40 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 40 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" are feeling and how positive or nagative they will be.\r\n");
            
            #line 41 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowMoodString && !string.IsNullOrWhiteSpace(this.Initiator.MoodString)) { 
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s overall mood is ");
            
            #line 42 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.MoodString));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 43 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowMoodString && !string.IsNullOrWhiteSpace(this.Recipient.MoodString)) { 
            
            #line default
            #line hidden
            
            #line 45 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s overall mood is ");
            
            #line 45 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.MoodString));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 46 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowFullName) {
            
            #line default
            #line hidden
            this.Write("Sometimes people are refered to by their full name.  This is usually a sign of re" +
                    "spect or formality.\r\nSometimes people are refered to by just their last name.  T" +
                    "his is usually a sign of friendship or intimacy.\r\n");
            
            #line 50 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   if (!string.IsNullOrWhiteSpace(this.Initiator.FullName)) { 
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s full name is ");
            
            #line 51 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.FullName));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 52 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   if (!string.IsNullOrWhiteSpace(this.Recipient.FullName)) { 
            
            #line default
            #line hidden
            
            #line 54 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s full name is ");
            
            #line 54 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.FullName));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 55 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 56 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 57 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowAgeRaceAndGender) {
            
            #line default
            #line hidden
            this.Write("Use age, race, and gender help to understand their perspective and how they might" +
                    " react to different situations. \r\n");
            
            #line 59 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s is a ");
            
            #line 59 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Gender));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 59 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Race));
            
            #line default
            #line hidden
            this.Write(" age ");
            
            #line 59 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Age));
            
            #line default
            #line hidden
            this.Write(" years old.\r\n");
            
            #line 60 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   if (!string.IsNullOrWhiteSpace(this.Recipient.NickName)) { 
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s is a ");
            
            #line 61 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.Gender));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 61 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.Race));
            
            #line default
            #line hidden
            this.Write(" age ");
            
            #line 61 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.Age));
            
            #line default
            #line hidden
            this.Write(" years old.\r\n");
            
            #line 62 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 63 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 64 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowDescription) {
            
            #line default
            #line hidden
            
            #line 65 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   if (this.Initiator.Description == this.Recipient.Description) { 
            
            #line default
            #line hidden
            this.Write("Both ");
            
            #line 66 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 66 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" are ");
            
            #line 66 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Description));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 67 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } else { 
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s is ");
            
            #line 68 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Description));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     if (!string.IsNullOrWhiteSpace(this.Recipient.NickName)) { 
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s is ");
            
            #line 70 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.Description));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 71 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } 
            
            #line default
            #line hidden
            
            #line 72 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowPawnType) { 
            
            #line default
            #line hidden
            
            #line 75 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   if (this.Initiator.IsColonist && this.Recipient.IsColonist) { 
            
            #line default
            #line hidden
            this.Write("Both ");
            
            #line 76 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 76 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" are colonists and members of the player\'s colony.\r\n");
            
            #line 77 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } else if (this.Initiator.IsPrisoner && this.Recipient.IsPrisoner) { 
            
            #line default
            #line hidden
            this.Write("Both ");
            
            #line 78 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 78 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" are prisoners. In RimWorld, prisoners are both assets and risks. Colonists house" +
                    " them in prison cells, meeting needs like food, care, and recreation to prevent " +
                    "escapes. Prisoners can be recruited, traded, or exploited for labor or medical r" +
                    "esources.\r\n");
            
            #line 79 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } else if (this.Initiator.IsHostile && this.Recipient.IsHostile) { 
            
            #line default
            #line hidden
            this.Write("Both ");
            
            #line 80 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 80 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" are raiders and are here to attack the player\'s colony.\r\n");
            
            #line 81 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } else { 
            
            #line default
            #line hidden
            
            #line 82 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     if (this.Initiator.IsColonist) { 
            
            #line default
            #line hidden
            
            #line 83 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" is a colonist and a member of the player\'s colony.  \r\n");
            
            #line 84 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } else if (this.Initiator.IsPrisoner) { 
            
            #line default
            #line hidden
            
            #line 85 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" is a prisoner.  In RimWorld, prisoners are both assets and risks. Colonists hous" +
                    "e them in prison cells, meeting needs like food, care, and recreation to prevent" +
                    " escapes. Prisoners can be recruited, traded, or exploited for labor or medical " +
                    "resources.\r\n");
            
            #line 86 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } else if (this.Initiator.IsHostile) { 
            
            #line default
            #line hidden
            
            #line 87 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" is a raider and is here to attack the player\'s colony.\r\n");
            
            #line 88 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } else if (!this.Initiator.IsAnimal) { 
            
            #line default
            #line hidden
            
            #line 89 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" is an NPC and just a temporary visitor here.  They are probably here as part of " +
                    "a trade caravan.\r\n");
            
            #line 90 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } 
            
            #line default
            #line hidden
            
            #line 91 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     if (this.Recipient.IsColonist) { 
            
            #line default
            #line hidden
            
            #line 92 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" is a colonist and a member of the player\'s colony.  \r\n");
            
            #line 93 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } else if (this.Recipient.IsPrisoner) { 
            
            #line default
            #line hidden
            
            #line 94 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" is a prisoner. In RimWorld, prisoners are both assets and risks. Colonists house" +
                    " them in prison cells, meeting needs like food, care, and recreation to prevent " +
                    "escapes. Prisoners can be recruited, traded, or exploited for labor or medical r" +
                    "esources.\r\n");
            
            #line 95 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } else if (this.Recipient.IsHostile) { 
            
            #line default
            #line hidden
            
            #line 96 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" is a raider and is here to attack the player\'s colony.\r\n");
            
            #line 97 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } else if (!string.IsNullOrWhiteSpace(this.Recipient.NickName) && !this.Recipient.IsAnimal) { 
            
            #line default
            #line hidden
            
            #line 98 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" is an NPC and just a temporary visitor here.\r\n");
            
            #line 99 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } 
            
            #line default
            #line hidden
            
            #line 100 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 101 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 102 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowAdulthood && !string.IsNullOrWhiteSpace(this.Initiator.Adulthood)) { 
            
            #line default
            #line hidden
            
            #line 103 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s adulthood was spent as: ");
            
            #line 103 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Adulthood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 104 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 105 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowAdulthood && !string.IsNullOrWhiteSpace(this.Recipient.Adulthood)) { 
            
            #line default
            #line hidden
            
            #line 106 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s adulthood was spent as: ");
            
            #line 106 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.Adulthood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 107 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 108 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowChildhood && !string.IsNullOrWhiteSpace(this.Initiator.Childhood)) { 
            
            #line default
            #line hidden
            
            #line 109 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s childhood was spent as: ");
            
            #line 109 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.Childhood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 110 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 111 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowChildhood && !string.IsNullOrWhiteSpace(this.Recipient.Childhood)) { 
            
            #line default
            #line hidden
            
            #line 112 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s childhood was spent as: ");
            
            #line 112 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.Childhood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 113 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 114 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowRoyaltyTitle && !string.IsNullOrWhiteSpace(this.Initiator.RoyaltyTitle)) { 
            
            #line default
            #line hidden
            
            #line 115 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" is royalty. Pawns speak differently to royalty, often with more respect and form" +
                    "ality.\r\n");
            
            #line 116 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s royal title is ");
            
            #line 116 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.RoyaltyTitle));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 117 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 118 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowRoyaltyTitle && !string.IsNullOrWhiteSpace(this.Recipient.RoyaltyTitle)) { 
            
            #line default
            #line hidden
            
            #line 119 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.RoyaltyTitle));
            
            #line default
            #line hidden
            this.Write(" is royalty. Pawns speak differently to royalty, often with more respect and form" +
                    "ality.\r\n");
            
            #line 120 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s royal title is ");
            
            #line 120 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.RoyaltyTitle));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 121 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 122 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowFaction) { 
            
            #line default
            #line hidden
            
            #line 123 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   if (this.Initiator.FactionName == this.Recipient.FactionName) { 
            
            #line default
            #line hidden
            this.Write("Both ");
            
            #line 124 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 124 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" belong to the same faction, called \"");
            
            #line 124 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.FactionName));
            
            #line default
            #line hidden
            this.Write("\". It is a ");
            
            #line 124 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.FactionLabel));
            
            #line default
            #line hidden
            this.Write(" faction. ");
            
            #line 124 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.FactionDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 125 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } else { 
            
            #line default
            #line hidden
            
            #line 126 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     if (!string.IsNullOrWhiteSpace(this.Initiator.FactionName)) { 
            
            #line default
            #line hidden
            this.Write(" \r\nThe faction ");
            
            #line 127 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" belongs to is called \"");
            
            #line 127 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.FactionName));
            
            #line default
            #line hidden
            this.Write("\". It is a ");
            
            #line 127 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.FactionLabel));
            
            #line default
            #line hidden
            this.Write(" faction. ");
            
            #line 127 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.FactionDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 128 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } 
            
            #line default
            #line hidden
            
            #line 129 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     if (!string.IsNullOrWhiteSpace(this.Recipient.FactionName)) { 
            
            #line default
            #line hidden
            this.Write(" \r\nThe faction ");
            
            #line 130 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" belongs to is called \"");
            
            #line 130 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.FactionName));
            
            #line default
            #line hidden
            this.Write("\". It is a ");
            
            #line 130 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.FactionLabel));
            
            #line default
            #line hidden
            this.Write(" faction. ");
            
            #line 130 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.FactionDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 131 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } 
            
            #line default
            #line hidden
            
            #line 132 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   } 
            
            #line default
            #line hidden
            
            #line 133 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 134 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
 if (this.Config.ShowIdeology) { 
            
            #line default
            #line hidden
            
            #line 135 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s and ");
            
            #line 135 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology strongy affect how they see the world.\r\n");
            
            #line 136 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
   if (!string.IsNullOrWhiteSpace(this.Initiator.IdeologyName) && this.Initiator.IdeologyName == this.Recipient.IdeologyName) { 
            
            #line default
            #line hidden
            this.Write("Both ");
            
            #line 137 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write(" and ");
            
            #line 137 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write(" share the same ideology, called \"");
            
            #line 137 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.IdeologyName));
            
            #line default
            #line hidden
            this.Write("\".\r\nThe narrative of \"");
            
            #line 138 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.IdeologyName));
            
            #line default
            #line hidden
            this.Write("\" is: ");
            
            #line 138 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.IdeologyDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 139 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     if (this.Config.ShowPrecepts && this.Initiator.IdeologyPrecepts.Any()) {
            
            #line default
            #line hidden
            this.Write("The precepts of their ideology are: ");
            
            #line 140 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(" ", this.Initiator.IdeologyPrecepts)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 141 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
     } 
            
            #line default
            #line hidden
            
            #line 142 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
  } else { 
            
            #line default
            #line hidden
            
            #line 143 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
    if (!string.IsNullOrWhiteSpace(this.Initiator.IdeologyName)) { 
            
            #line default
            #line hidden
            
            #line 144 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology is \"");
            
            #line 144 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.IdeologyName));
            
            #line default
            #line hidden
            this.Write("\".\r\nThe narrative of \"");
            
            #line 145 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.IdeologyName));
            
            #line default
            #line hidden
            this.Write("\" is: ");
            
            #line 145 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.IdeologyDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 146 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
      if (this.Config.ShowPrecepts && this.Initiator.IdeologyPrecepts.Any()) {
            
            #line default
            #line hidden
            this.Write("The precepts of ");
            
            #line 147 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Initiator.NickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology are: ");
            
            #line 147 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(" ", this.Recipient.IdeologyPrecepts)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 148 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
      } 
            
            #line default
            #line hidden
            
            #line 149 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
    } 
            
            #line default
            #line hidden
            
            #line 150 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
    if (!string.IsNullOrWhiteSpace(this.Recipient.IdeologyName)) { 
            
            #line default
            #line hidden
            
            #line 151 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology is ");
            
            #line 151 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.IdeologyName));
            
            #line default
            #line hidden
            this.Write(".\r\nThe narrative of this ideology is: ");
            
            #line 152 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.IdeologyDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 153 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
      if (this.Config.ShowPrecepts && this.Recipient.IdeologyPrecepts.Any()) {
            
            #line default
            #line hidden
            this.Write("The precepts of ");
            
            #line 154 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Recipient.NickName));
            
            #line default
            #line hidden
            this.Write("\'s ideology are: ");
            
            #line 154 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(" ", this.Recipient.IdeologyPrecepts)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 155 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
      } 
            
            #line default
            #line hidden
            
            #line 156 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
	  } 
            
            #line default
            #line hidden
            
            #line 157 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 158 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\InitiatorRecipientTemplate.tt"
} 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class InitiatorRecipientTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
