// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RimDialogueObjects.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using RimDialogue.Core;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class PawnTemplate : PawnTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nYou are a character writer for the game RimWorld a sci-fi colony simulation gam" +
                    "e set on a distant, lawless planet.\r\nYour job is to create a one sentence charac" +
                    "ter profile of, ");
            
            #line 9 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write(", based on the data provided below:\r\n\r\n");
            
            #line 11 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Pawn.Personality)) { 
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s personality is ");
            
            #line 12 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.Personality));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 13 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.PersonalityDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 15 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Pawn.MoodString)) { 
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s overall mood is ");
            
            #line 16 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.MoodString));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 17 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Pawn.FullName)) { 
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s full name is ");
            
            #line 19 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.FullName));
            
            #line default
            #line hidden
            this.Write(".\r\n");
            
            #line 20 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s is a ");
            
            #line 21 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.Gender));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.Race));
            
            #line default
            #line hidden
            this.Write(" age ");
            
            #line 21 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.Age));
            
            #line default
            #line hidden
            this.Write(" years old.\r\n");
            
            #line 22 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s is ");
            
            #line 22 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.Description));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 23 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
  if (this.Pawn.IsColonist) { 
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write(" is a colonist and a member of the player\'s colony.  \r\n");
            
            #line 25 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
  } else if (this.Pawn.IsPrisoner) { 
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write(" is a prisoner.  In RimWorld, prisoners are both assets and risks. Colonists hous" +
                    "e them in prison cells, meeting needs like food, care, and recreation to prevent" +
                    " escapes. Prisoners can be recruited, traded, or exploited for labor or medical " +
                    "resources.\r\n");
            
            #line 27 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
  } else if (this.Pawn.IsHostile) { 
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write(" is a raider and is here to attack the player\'s colony.\r\n");
            
            #line 29 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
  } else if (!this.Pawn.IsAnimal) { 
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write(" is an NPC and just a temporary visitor here.  They are probably here as part of " +
                    "a trade caravan.\r\n");
            
            #line 31 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Pawn.Adulthood)) { 
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s previous occupation was: ");
            
            #line 33 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.Adulthood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 34 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Pawn.Childhood)) { 
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s childhood was spent as: ");
            
            #line 36 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.Childhood));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 37 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Pawn.RoyaltyTitle)) { 
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write(" is royalty. Pawns speak differently to royalty, often with more respect and form" +
                    "ality.\r\n");
            
            #line 40 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s royal title is ");
            
            #line 40 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.RoyaltyTitle));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 41 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (!string.IsNullOrWhiteSpace(this.Pawn.FactionName)) { 
            
            #line default
            #line hidden
            this.Write(" \r\nThe faction ");
            
            #line 43 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write(" belongs to is called \"");
            
            #line 43 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.FactionName));
            
            #line default
            #line hidden
            this.Write("\". It is a ");
            
            #line 43 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.FactionLabel));
            
            #line default
            #line hidden
            this.Write(" faction. ");
            
            #line 43 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.FactionDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 44 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 45 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (this.Pawn.Skills.Any()) { 
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s skills are: \r\n");
            
            #line 47 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(",\r\n", this.Pawn.Skills)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 48 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 if (this.Pawn.Traits.Any()) { 
            
            #line default
            #line hidden
            
            #line 50 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Pawn.NickName));
            
            #line default
            #line hidden
            this.Write("\'s traits are: \r\n");
            
            #line 51 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(" ", this.Pawn.Traits)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 52 "C:\Users\madja\source\repos\RImDialogueServer\RimDialogueObjects\Templates\PawnTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nIt is important that you respond with only the character profile.");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class PawnTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
